/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maxitoners.iu;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import maxitoners.DAOentidades.ClienteDAO;
import maxitoners.DAOentidades.ImpresoraDAO;
import maxitoners.DAOentidades.RegistroDAO;
import maxitoners.entidades.Cliente;
import maxitoners.entidades.Impresora;
import maxitoners.entidades.Registro;
import static maxitoners.iu.Inicio.fechaActual;

/**
 *
 * @author luism
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
        cargarDatos();
        cambiarLblFecha();
        ConfigVentanas.configurarVentana(this, "Maxitoners");
    }

    public void cargarDatos() {
        DefaultTableModel tablaClientes = (DefaultTableModel) tblCliente.getModel();
        ClienteDAO clienteDao = new ClienteDAO();
        tablaClientes.setRowCount(0);

        try {
            List<Cliente> clientes = clienteDao.getAllClientes();
            for (Cliente cliente : clientes) {
                tablaClientes.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getNombre(),
                    cliente.getDireccion(),
                    cliente.getRfc()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar los datos de la tabla.");
        }

        DefaultTableModel tablaImpresoras = (DefaultTableModel) tblImpresora.getModel();
        ImpresoraDAO impresoraDao = new ImpresoraDAO();
        tablaImpresoras.setRowCount(0);

        try {
            List<Impresora> impresoras = impresoraDao.getAllImpresoras();
            for (Impresora impresora : impresoras) {
                tablaImpresoras.addRow(new Object[]{
                    impresora.getId(),
                    impresora.getMarca(),
                    impresora.getModelo(),
                    impresora.getNumeroSerie()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar los datos de la tabla.");
        }
        
        DefaultTableModel tablaRegistros = (DefaultTableModel) tblRegistros.getModel();
        RegistroDAO registroDAO = new RegistroDAO();
        tablaRegistros.setRowCount(0);
        
        try {
            List<Registro> registros = registroDAO.getAllRegistros();
            for(Registro registro : registros){
                tablaRegistros.addRow(new Object[]{
                    registro.getId(),
                    registro.getMarcaImpresora() + " " + registro.getModeloImpresora(),
                    registro.getNombreCliente(),
                    registro.getNumImpresiones(),
                    registro.getFecha()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar los datos de la tabla.");
        }

    }
    
    private void cambiarLblFecha(){
        lblFecha.setText("Fecha: " + fechaActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCliente = new javax.swing.JRadioButton();
        btnImpresora = new javax.swing.JRadioButton();
        btnRegistros = new javax.swing.JRadioButton();
        txfBuscador = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        spCliente = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        spImpresora = new javax.swing.JScrollPane();
        tblImpresora = new javax.swing.JTable();
        spRegistros = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consulta");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxitoners/imgs/Maxitoners Logo.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(222, 189));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAtras.setBackground(new java.awt.Color(255, 0, 51));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Volver");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(14, 14, 14)
                        .addComponent(btnAtras)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        btnCliente.setBackground(new java.awt.Color(102, 102, 0));
        Grupo1.add(btnCliente);
        btnCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnCliente.setSelected(true);
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnImpresora.setBackground(new java.awt.Color(102, 102, 0));
        Grupo1.add(btnImpresora);
        btnImpresora.setForeground(new java.awt.Color(0, 0, 0));
        btnImpresora.setText("Impresora");
        btnImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpresoraActionPerformed(evt);
            }
        });

        btnRegistros.setBackground(new java.awt.Color(102, 102, 0));
        Grupo1.add(btnRegistros);
        btnRegistros.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistros.setText("Registros");
        btnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosActionPerformed(evt);
            }
        });

        txfBuscador.setBackground(new java.awt.Color(102, 102, 0));
        txfBuscador.setForeground(new java.awt.Color(255, 255, 255));
        txfBuscador.setText("Buscar...");
        txfBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quitarTexto(evt);
            }
        });
        txfBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBuscadorActionPerformed(evt);
            }
        });
        txfBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfBuscadorKeyReleased(evt);
            }
        });

        jPanel7.setLayout(new java.awt.CardLayout());

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Dirección", "RFC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        spCliente.setViewportView(tblCliente);
        if (tblCliente.getColumnModel().getColumnCount() > 0) {
            tblCliente.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel7.add(spCliente, "card2");

        tblImpresora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Modelo", "No. Serie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblImpresora.setGridColor(new java.awt.Color(255, 255, 255));
        tblImpresora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblImpresoraMouseClicked(evt);
            }
        });
        spImpresora.setViewportView(tblImpresora);
        if (tblImpresora.getColumnModel().getColumnCount() > 0) {
            tblImpresora.getColumnModel().getColumn(0).setResizable(false);
            tblImpresora.getColumnModel().getColumn(1).setResizable(false);
            tblImpresora.getColumnModel().getColumn(2).setResizable(false);
            tblImpresora.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel7.add(spImpresora, "card3");

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Impresora", "Cliente", "Numero de Impresiones", "Fecha"
            }
        ));
        spRegistros.setViewportView(tblRegistros);

        jPanel7.add(spRegistros, "card4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txfBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnRegistros))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImpresora)
                    .addComponent(btnCliente)
                    .addComponent(txfBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpresoraActionPerformed
        spImpresora.setVisible(true);
        spCliente.setVisible(false);
        spRegistros.setVisible(false);
    }//GEN-LAST:event_btnImpresoraActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        spCliente.setVisible(true);
        spImpresora.setVisible(false);
        spRegistros.setVisible(false);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void quitarTexto(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quitarTexto
        String texto = "Buscar...";
        if (txfBuscador.getText().contentEquals(texto)) {
            txfBuscador.setText("");
        }
    }//GEN-LAST:event_quitarTexto

    private void txfBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBuscadorActionPerformed
        // NO SE USA
    }//GEN-LAST:event_txfBuscadorActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked

    }//GEN-LAST:event_tblClienteMouseClicked

    private void tblImpresoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImpresoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblImpresoraMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Inicio ventanaInicio = new Inicio();

        ventanaInicio.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    // Buscador
    private void txfBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfBuscadorKeyReleased
        String filtro = txfBuscador.getText();

        DefaultTableModel tablaClientes = (DefaultTableModel) tblCliente.getModel();
        ClienteDAO clienteDao = new ClienteDAO();
        tablaClientes.setRowCount(0);

        try {
            List<Cliente> clientes = clienteDao.getByName(filtro);
            for (Cliente cliente : clientes) {
                tablaClientes.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getNombre(),
                    cliente.getDireccion(),
                    cliente.getRfc()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar los datos de la tabla.");
        }
        
        DefaultTableModel tablaImpresoras = (DefaultTableModel) tblImpresora.getModel();
        ImpresoraDAO impresoraDao = new ImpresoraDAO();
        tablaImpresoras.setRowCount(0);
        
        try {
            List<Impresora> impresoras = impresoraDao.getByMarca(filtro);
            for(Impresora impresora : impresoras){
                tablaImpresoras.addRow(new Object[]{
                    impresora.getId(),
                    impresora.getMarca(),
                    impresora.getModelo(),
                    impresora.getNumeroSerie()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar los datos de la tabla.");
        }
    }//GEN-LAST:event_txfBuscadorKeyReleased

    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosActionPerformed
        spRegistros.setVisible(true);
        spCliente.setVisible(false);
        spImpresora.setVisible(false);
    }//GEN-LAST:event_btnRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JButton btnAtras;
    private javax.swing.JRadioButton btnCliente;
    private javax.swing.JRadioButton btnImpresora;
    private javax.swing.JRadioButton btnRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JScrollPane spCliente;
    private javax.swing.JScrollPane spImpresora;
    private javax.swing.JScrollPane spRegistros;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblImpresora;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txfBuscador;
    // End of variables declaration//GEN-END:variables
}
